#! /bin/bash

# Copyright 2014 Gleetr SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Pre-requisite: you need jq - http://stedolan.github.io/jq/
# set -x

CURL_ARGS=$@

AUTH0_DOMAIN=cef.auth0.com
AUTH0_CLIENTID=$(sed -n '1p' .passwd)
AUTH0_USERNAME=$(sed -n '2p' .passwd)
AUTH0_PASSWORD=$(sed -n '3p' .passwd)

# AUTH0_SCOPE='openid email'
AUTH0_SCOPE="profile openid email"

TOKEN_URL=https://${AUTH0_DOMAIN}/oauth/token
TOKEN_PAYLOAD="{
   \"client_id\":   \"${AUTH0_CLIENTID}\",
   \"username\":    \"${AUTH0_USERNAME}\",
   \"password\":    \"${AUTH0_PASSWORD}\",
   \"audience\":    \"https://ceftb.org/api/v1\",
   \"realm\":       \"Username-Password-Authentication\",
   \"grant_type\":  \"password\",
   \"scope\":       \"${AUTH0_SCOPE}\",
   \"device\":      \"\"
}"

# call Auth0 to retrieve the JWT
JWT=$(echo ${TOKEN_PAYLOAD} | curl -s ${CURL_VERBOSE} -X POST --header 'Content-Type: application/json' --data-binary @- ${TOKEN_URL})

# extract the id_token in the JWT
ACCESS_TOKEN=$(echo ${JWT} | grep -Po '"access_token":.*?[^\\]"' | cut -d ':' -f 2 | tr -d '"')

# execute the asked cURL with the correct Authorization header
echo $ACCESS_TOKEN
